Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2018-09, with the labels that each got.

#191 Make the ID registry about the EBML Header only
  specification.markdown
Labels: clarifications, enhancement

#192 bump to 07
  Makefile
  rfc_frontmatter.markdown
Labels: formatting

#181 add DocTypeExtension to handle experimental elements and regular extensions
  specification.markdown
Labels: format addition

#194 Extension precision
  specification.markdown
Labels: clarifications
