Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2018-08, with the labels that each got.

#179 IANA considerations for Element ID allocation
  specification.markdown
Labels: clarifications, enhancement

#177 start section on reading bad data
  specification.markdown
Labels: clarifications, enhancement

#189 clarify ebml header allowances
  specification.markdown
Labels: clarifications

#186 bump to version 06
  Makefile
  rfc_frontmatter.markdown
Labels: formatting

#188 add doctype registry to iana considerations
  specification.markdown
Labels: enhancement
