Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2019-12, with the labels that each got.

#302 Remove occurences from the path
  specification.markdown
Labels: XML Schema, clarifications, enhancement

#306 Response to 2019 12 03 review
  rfc_backmatter.markdown
  specification.markdown
Labels: clarifications

#309 add captions to remaining uncaptioned tables
  specification.markdown
Labels: clarifications, enhancement, formatting

#313 Updates from adam's review
  specification.markdown
Labels: clarifications, formatting

#311 don't make EBML too generic
  rfc_frontmatter.markdown
Labels: clarifications

#310 add statement about uniqueness of id and path within an ebml schema
  specification.markdown
Labels: clarifications, enhancement

#318 the Parent element is the Master directly before the EBML Element
  specification.markdown
Labels: clarifications

#319 reword invalid Global Element in unknown length element table
  specification.markdown
Labels: clarifications

#321 mention the IANA Registry in the Doctype text.
  specification.markdown
Labels: clarifications

#323 fix EBML Element attributes reference
  specification.markdown
Labels: formatting

#325 XSD add default values to unknownsizeallowed/recurring
  EBMLSchema.xsd
Labels: XML Schema, enhancement

#327 endianness is on bytes/octets
  specification.markdown
Labels: bug, clarifications

#328 Reword the initial paragraph of Extending the Element Data Size
  specification.markdown
Labels: clarifications

#330 add the missing recursive attribute in EBMLSchema.xsd
  EBMLSchema.xsd
Labels: XML Schema, bug

#320 UTF-8 strings with NULL must still be valid UTF-8
  specification.markdown
Labels: clarifications
