Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2019-07, with the labels that each got.

#274 EBML Schema example: fix the documentation 'purpose' attribute
  ebml_schema_example.xml
Labels: bug, enhancement

#273 XSD: allow basic HTML tags to be used in documentation
  EBMLSchema.xsd
Labels: XSD, enhancement

#272 XSD: rename recursive to recurring
  EBMLSchema.xsd
Labels: XSD, bug, enhancement

#265 updates from ietf review
  specification.markdown
Labels: clarifications, formatting

#275 document xhtml tags in documentation element
  specification.markdown
Labels: clarifications, enhancement

#277 Revert 640fbb71fb102f73948857bd97f7330d237bd5d6
  specification.markdown
Labels: clarifications

#271 add implementation_note element
  EBMLSchema.xsd
  specification.markdown
Labels: XML Schema, clarifications, enhancement

#278 Ignore extra max occurences
  specification.markdown
Labels: clarifications

#270 Add ebml extension element
  EBMLSchema.xsd
  specification.markdown
Labels: XML Schema, enhancement, formatting
