Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2019-09, with the labels that each got.

#257 Clarify the unknown size use
  specification.markdown
Labels: clarifications, enhancement, formatting

#281 Add more Global elements explanations
  specification.markdown
Labels: clarifications, enhancement

#284 bump to version 12
  Makefile
  rfc_frontmatter.markdown
Labels: formatting
