Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2019-01, with the labels that each got.

#201 reference RFC8174 and BCP14 for the normative keywords
  specification.markdown
Labels: clarifications

#204 the zero-padding of VINT_DATA is a MUST
  specification.markdown
Labels: enhancement

#199 mention that EBML is defined mostly for the purpose of Matroska
  specification.markdown
Labels: clarifications, enhancement

#207 update citations for RFC8126
  specification.markdown
Labels: clarifications, enhancement

#202 Error mitigation
  specification.markdown
Labels: clarifications, enhancement

#200 add versioning paragraphs
  specification.markdown
Labels: clarifications, enhancement

#216 mention the range for printable ASCII
  specification.markdown
Labels: clarifications

#213 the DocType MUST be unique in a Schema
  specification.markdown
Labels: clarifications
