Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2019-10, with the labels that each got.

#255 Update to mmark 2.0.40
  .gitignore
  Makefile
  bootstrap
  rfc_backmatter.markdown
  rfc_frontmatter.markdown
  specification.markdown
  tools.mak
Labels: formatting

#288 rename note_type to note_atttribute to make it clear we add rule on an attribute
  EBMLSchema.xsd
  specification.markdown
Labels: clarifications

#291 Xml2rfc version 3 updates
  Makefile
  specification.markdown
Labels: formatting

#297 Add implementation_note example
  specification.markdown
Labels: clarifications, enhancement

#300 Add xpaths to clarify position of description ebml schema elements
  specification.markdown
Labels: clarifications
