Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2020-06, with the labels that each got.

#340 Documentation definition fixes
  specification.markdown
Labels: bug

#346 Fix the GlobalParentOccurence spelling
  specification.markdown
Labels: bug, clarifications

#350 Apply the recursive punctuation change mentioned in AUTH48 12)
  specification.markdown
Labels: clarifications

#352 Use consistent formatting for the id declarations
  specification.markdown
Labels: formatting

#348 add missing for in the range description
  specification.markdown
Labels: bug, formatting

#354 Use the plural form of semantic when used as a noun
  specification.markdown
Labels: bug, clarifications

#342 turn "xsd" sourcecode tag into "xml" tag
  Makefile
Labels: bug, formatting

#349 Clean bool attributes text
  specification.markdown
Labels: clarifications

#355 fixed bullet-point text style
  specification.markdown
Labels: clarifications

#344 add some keywords to the document for easier searching in the RFCs
  rfc_frontmatter.markdown
Labels: build system

#343 rewrite introduction line as proposed during AUTH48
  specification.markdown
Labels: clarifications

#353 Reword the DocTypeExtensionVersion support requirements
  specification.markdown
Labels: clarifications

#345 reword the EBMLSchema XML usage as suggested in AUTH48
  specification.markdown
Labels: clarifications

#347 Clarify the big-endian storage of the EBML ID
  specification.markdown
Labels: clarifications

#356 Use the 2003 correction of the ITU V42 CRC
  rfc_backmatter.markdown
  specification.markdown
Labels: bug

#358 add the first version of the rfc8794 XML source
  rfc-editor/rfc8794.xml
Labels: formatting
