Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2020-01, with the labels that each got.

#332 delete not rendered italic
  signature.markdown
Labels: formatting

#333 add CRC32 in the possible disarding of data in the security considerations
  specification.markdown
Labels: clarifications, enhancement

#334 remove sourcecode workaround
  Makefile
Labels: build system

#335 bump to version 18
  Makefile
  rfc_frontmatter.markdown
Labels: build system
