Repository ietf-wg-cellar/ebml-specification, pull requests merged in 2022-10, with the labels that each got.

#421 update the power of two formulas to match the RFC text
  specification.markdown
Labels: formatting

#414 Range and number of valid element IDs
  specification.markdown
Labels: errata-rfc8794

#419 EBML Schema XML: adjust reference to 'mastroska' DocType
  ebml.xml
Labels: bug, errata-rfc8794
